In [39]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd

## Maldición de dimensionalidad y polynomial features
#### En estadistica la maldicion de dimensionalidad es también conocida como efecto Hughes, se refiere a los diversos fenómenos que surgen al analizar y organizar datos de espacios de múltiples dimensiones, en nuestro caso los aplicaremos a datasets que simulan multiples variables. En el caso de polynomial features son todas las combinaciones polinomiales de las features con grado menor o igual que el grado especificado en la funcion, por ejemplo si hay un input de dos dimensiones la forma de grado dos polinomial para el conjunto a,b seria el siguiente [1, a, b, a^2, ab, b^2].


#### Random values de 1 feature y 10 observaciones  d0=10,  d1=1, LAS CUALES SE CONVIERTEN EN 3 FEATURES

In [46]:
var1 = np.random.rand(10,1)
print('Valores', var1)
print('')
print('Polinomiales')
var_pol1 = PolynomialFeatures(3)
pd.DataFrame(var_pol1.fit_transform(var1))

Valores [[0.71505224]
 [0.17438732]
 [0.1496681 ]
 [0.10782193]
 [0.66051449]
 [0.4266513 ]
 [0.60324753]
 [0.45904457]
 [0.21150352]
 [0.76756274]]

Polinomiales


0         1         2         3
0  1.0  0.715052  0.511300  0.365606
1  1.0  0.174387  0.030411  0.005303
2  1.0  0.149668  0.022401  0.003353
3  1.0  0.107822  0.011626  0.001253
4  1.0  0.660514  0.436279  0.288169
5  1.0  0.426651  0.182031  0.077664
6  1.0  0.603248  0.363908  0.219526
7  1.0  0.459045  0.210722  0.096731
8  1.0  0.211504  0.044734  0.009461
9  1.0  0.767563  0.589153  0.452212

#### Random values de 2 features y 10 observaciones  d0=10,  d1=2, LAS CUALES SE CONVIERTEN EN 9 FEATURES

In [47]:
var2 = np.random.rand(10,2)
print('Valores', var1)
print('')
print('Polinomiales')
var_pol2 = PolynomialFeatures(3)
pd.DataFrame(var_pol1.fit_transform(var2))

Valores [[0.71505224]
 [0.17438732]
 [0.1496681 ]
 [0.10782193]
 [0.66051449]
 [0.4266513 ]
 [0.60324753]
 [0.45904457]
 [0.21150352]
 [0.76756274]]

Polinomiales


0         1         2         3         4         5         6         7  \
0  1.0  0.826596  0.928507  0.683260  0.767500  0.862126  0.564780  0.634412   
1  1.0  0.598815  0.918943  0.358579  0.550277  0.844457  0.214723  0.329514   
2  1.0  0.833462  0.244904  0.694659  0.204118  0.059978  0.578972  0.170125   
3  1.0  0.271804  0.696048  0.073877  0.189189  0.484483  0.020080  0.051422   
4  1.0  0.791718  0.718097  0.626818  0.568530  0.515663  0.496263  0.450116   
5  1.0  0.277213  0.725280  0.076847  0.201057  0.526031  0.021303  0.055735   
6  1.0  0.962149  0.140211  0.925730  0.134904  0.019659  0.890690  0.129798   
7  1.0  0.196840  0.065107  0.038746  0.012816  0.004239  0.007627  0.002523   
8  1.0  0.980268  0.622495  0.960925  0.610212  0.387500  0.941963  0.598171   
9  1.0  0.833329  0.961220  0.694437  0.801013  0.923944  0.578695  0.667507   

          8         9  
0  0.712630  0.800490  
1  0.505673  0.776008  
2  0.049989  0.014689  
3  0.131685  0.337224  
4  0.408260  0.370296  
5  0.145822  0.381519  
6  0.018915  0.002756  
7  0.000834  0.000276  
8  0.379854  0.241217  
9  0.769950  0.888114

#### Random values de 2 features y 10 observaciones  d0=10,  d1=3, LAS CUALES SE CONVIERTEN EN 19 FEATURES

In [48]:
var3 = np.random.rand(10,3)
print('Valores', var3)
print('')
print('Polinomiales')
var_pol3 = PolynomialFeatures(3)
pd.DataFrame(var_pol1.fit_transform(var3))

Valores [[3.27550237e-02 4.42247885e-01 3.04907109e-02]
 [1.64749103e-01 2.53848357e-01 4.12755510e-01]
 [1.98269661e-01 6.67362713e-01 8.49861041e-01]
 [1.04259306e-01 3.99573523e-01 5.84573110e-01]
 [7.94937119e-04 4.98589310e-01 8.21724310e-01]
 [6.05845982e-01 8.23208336e-01 1.17550851e-01]
 [2.90023131e-01 7.67539007e-01 4.81418707e-01]
 [2.02403719e-01 8.27059931e-01 4.76565737e-01]
 [4.13801168e-01 6.80808942e-01 1.72545469e-01]
 [2.85210021e-01 6.23880590e-01 8.97219610e-01]]

Polinomiales


0         1         2         3             4         5         6   \
0  1.0  0.032755  0.442248  0.030491  1.072892e-03  0.014486  0.000999   
1  1.0  0.164749  0.253848  0.412756  2.714227e-02  0.041821  0.068001   
2  1.0  0.198270  0.667363  0.849861  3.931086e-02  0.132318  0.168502   
3  1.0  0.104259  0.399574  0.584573  1.087000e-02  0.041659  0.060947   
4  1.0  0.000795  0.498589  0.821724  6.319250e-07  0.000396  0.000653   
5  1.0  0.605846  0.823208  0.117551  3.670494e-01  0.498737  0.071218   
6  1.0  0.290023  0.767539  0.481419  8.411342e-02  0.222604  0.139623   
7  1.0  0.202404  0.827060  0.476566  4.096727e-02  0.167400  0.096459   
8  1.0  0.413801  0.680809  0.172545  1.712314e-01  0.281720  0.071400   
9  1.0  0.285210  0.623881  0.897220  8.134476e-02  0.177937  0.255896   

         7         8         9             10            11            12  \
0  0.195583  0.013484  0.000930  3.514259e-05  4.744840e-04  3.271323e-05   
1  0.064439  0.104777  0.170367  4.471664e-03  6.890020e-03  1.120312e-02   
2  0.445373  0.567166  0.722264  7.794151e-03  2.623460e-02  3.340877e-02   
3  0.159659  0.233580  0.341726  1.133299e-03  4.343365e-03  6.354311e-03   
4  0.248591  0.409703  0.675231  5.023407e-10  3.150711e-07  5.192682e-07   
5  0.677672  0.096769  0.013818  2.223754e-01  3.021581e-01  4.314696e-02   
6  0.589116  0.369508  0.231764  2.439484e-02  6.456033e-02  4.049377e-02   
7  0.684028  0.394148  0.227115  8.291927e-03  3.388238e-02  1.952359e-02   
8  0.463501  0.117470  0.029772  7.085576e-02  1.165759e-01  2.954520e-02   
9  0.389227  0.559758  0.805003  2.320034e-02  5.074941e-02  7.298411e-02   

         13        14        15        16        17        18        19  
0  0.006406  0.000442  0.000030  0.086496  0.005963  0.000411  0.000028  
1  0.010616  0.017262  0.028068  0.016358  0.026598  0.043247  0.070320  
2  0.088304  0.112452  0.143203  0.297225  0.378505  0.482012  0.613824  
3  0.016646  0.024353  0.035628  0.063796  0.093332  0.136545  0.199764  
4  0.000198  0.000326  0.000537  0.123945  0.204274  0.336663  0.554854  
5  0.410565  0.058627  0.008372  0.557865  0.079661  0.011375  0.001624  
6  0.170857  0.107166  0.067217  0.452170  0.283612  0.177888  0.111576  
7  0.138450  0.079777  0.045969  0.565732  0.325984  0.187838  0.108235  
8  0.191797  0.048609  0.012320  0.315555  0.079975  0.020269  0.005137  
9  0.111011  0.159649  0.229595  0.242831  0.349222  0.502226  0.722265

### CONCLUSIONES
Cuando se aumenta el grado del polinomio se incrementa exponencialmente las features en el dataset